### PR TITLE
Upgrade to Laravel 10

### PR DESCRIPTION
**Pull request by danharrin**

### CODE REVIEW

**Comment by denisdulici** [comment]
Please, keep PHP 8.0 version as it is supported by [Laravel 9](https://laravel.com/docs/9.x/releases#support-policy).

**Comment by danharrin** [comment]
I've just removed it from the matrix, as Composer was refusing to install. The package still supports PHP 8

**Comment by danharrin** [comment]
if you want to add it back, you'll need to work out why the action is failing

**Comment by danharrin** [comment]
@denisdulici Laravel 10 is being released tomorrow, please merge and release this PR so that other packages like [filamentphp/filament](https://github.com/filamentphp/filament) are not blocked.

**Comment by denisdulici** [comment]
Will add Laravel 10 support, including PHP 8.0 version, as soon as it is released.

**Comment by RickDBCN** [comment]
@denisdulici Could you please merge this? This won't have any impact.

**Comment by josefbehr** [comment]
@denisdulici this PR does exactly this. It adds laravel 10 support without removing the possibility to still use this package with laravel 8 oder 9 and php 8.0. Just, as @danharrin wrote, the tests run by the github actions matrix fail, if they try to combine php 8.0 and laravel 10. If you need to test against php 8.0 still, you can find a way to do this later while already allowing any package and project that uses your package to update to laravel 10. Otherwise I suspect many a maintainer might go looking for alternatives, which would be a pity over such a small thing.

**Comment by danharrin** [comment]
I have just opened a new PR, #78, as @ryangjchandler taught me a neat trick where I can exclude the P8-L10 combo.

As @josefbehr said, please merge this @denisdulici, its genuinely blocking lots of people now L10 is released.

**Comment by SebastiaanKloos** [comment]
Please add this. I would really love to upgrade to Laravel 10!

**Pull request closed without merging**
